# Top-level keys (directly accessible)
GEMINI_API = "AIzaSyD4BxdUl5mpMyQRq7f736SvdaZyWNrKvdU"

# Section keys (accessed via st.secrets.general.api_key)
[general]
api_key = "AIzaSyD4BxdUl5mpMyQRq7f736SvdaZyWNrKvdU"